crunchbase_category_groups:
  - id
  - name
  - category_groups_list
crunchbase_funding_rounds:
  - id
  - announced_on
  - cb_url
  - city
  - country
  - country_code
  - created_at
  - investment_type
  - investor_count
  - lead_investor_ids
  - location_id
  - name
  - org_id
  - org_name
  - permalink
  - post_money_valuation
  - post_money_valuation_currency_code
  - post_money_valuation_usd
  - raised_amount
  - raised_amount_currency_code
  - raised_amount_usd
  - rank
  - region
  - state_code
  - type
  - updated_at
crunchbase_investments:
  - id
  - cb_url
  - created_at
  - funding_round_id
  - funding_round_name
  - investor_id
  - investor_name
  - is_lead_investor
  - name
  - partner_name
  - permalink
  - rank
  - type
  - updated_at
  - investor_type
crunchbase_investors:
  - id
  - cb_url
  - city
  - closed_on
  - country
  - country_code
  - created_at
  - domain
  - facebook_url
  - founded_on
  - investment_count
  - investor_types
  - linkedin_url
  - location_id
  - logo_url
  - name
  - permalink
  - rank
  - region
  - roles
  - state_code
  - total_funding
  - total_funding_currency_code
  - total_funding_usd
  - twitter_url
  - type
  - updated_at
crunchbase_organizations:
  - id
  - address
  - alias1
  - alias2
  - alias3
  - cb_url
  - city
  - closed_on
  - country
  - country_code
  - created_at
  - domain
  - email
  - employee_count
  - facebook_url
  - founded_on
  - homepage_url
  - is_health
  - last_funding_on
  - legal_name
  - linkedin_url
  - location_id
  - logo_url
  - long_description
  - mesh_terms
  - name
  - num_exits
  - num_funding_rounds
  - parent_id
  - permalink
  - phone
  - postal_code
  - primary_role
  - rank
  - region
  - roles
  - short_description
  - state_code
  - status
  - total_funding
  - total_funding_currency_code
  - total_funding_usd
  - twitter_url
  - type
  - updated_at
crunchbase_organizations_categories:
  - category_name
  - organization_id
