crunchbase_organizations:
  - name
  - city
  - country
  - country_code
  - employee_count
  - founded_on
  - closed_on
  - short_description
  - long_description
  - primary_role
  - roles
  - status
  - updated_at
  - total_funding
  - total_funding_currency_code
  - total_funding_usd
  - num_exits
  - num_funding_rounds
crunchbase_organizations_categories:
  - category_name
  - organization_id
